---
title: "Table1"
author: "Kangguo Li"
date: "2022-11-22"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(DescrTab2)
library(tidyverse)
load('./xiamen.RData')
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
Data <- DataVaccine |> 
  mutate(LastVaccine = pmax(FirstVaccineDate,
                           SecondVaccineDate,
                           ThirdVaccineDate,
                           na.rm = T),
         VaccineRange = date - as.Date(LastVaccine)) |> 
  left_join(datafile[,1:2],
            by = c(Name = 'name')) |> 
  select(id, vaccine, age, gender, VaccineType, VaccineRange)

DataCtTable <- DataCtValue |> 
  group_by(CaseID) |> 
  summarise(maxCtN = min(CtN, na.rm = T),
            maxCtO = min(CtORF1ab, na.rm = T),
            OnsetDate = OnsetDate[1],
            datemaxN = SampleDate[which(CtN == maxCtN)[1]],
            datemaxO = SampleDate[which(CtORF1ab == maxCtO)[1]],
            datemaxN = round(as.numeric(datemaxN - OnsetDate)),
            datemaxO = round(as.numeric(datemaxO - OnsetDate)),
            rangeN = round(as.numeric(max(SampleDate[which(CtN < 30)], na.rm = T) -
                                        min(SampleDate[which(CtN < 30)], na.rm = T))),
            rangeO = round(as.numeric(max(SampleDate[which(CtORF1ab < 30)], na.rm = T) - 
                                        min(SampleDate[which(CtORF1ab < 30)], na.rm = T))),
            beforeN = min(SampleDate[which(CtN < 30)], na.rm = T) < OnsetDate,
            beforeO = min(SampleDate[which(CtORF1ab < 30)], na.rm = T) < OnsetDate,
            afterN = round(as.numeric(max(SampleDate[which(CtN < 30)], na.rm = T) - OnsetDate)),
            afterO = round(as.numeric(max(SampleDate[which(CtORF1ab < 30)], na.rm = T) - OnsetDate)),
            .groups = 'drop') |> 
  right_join(Data,
            by = c(CaseID = 'id')) |> 
  select(vaccine, age, gender, VaccineType, VaccineRange, 
         maxCtN, datemaxN, rangeN, beforeN, afterN,
         maxCtO, datemaxO, rangeO, beforeO, afterO)

group_labels <- list('Unfull Vaccination', 'Full Vaccination', 'Booster Dose')

descr(DataCtTable,
      group = 'vaccine',
      group_labels = group_labels,
      summary_stats_cont = list(
        median = DescrTab2:::.median,
        Q1 = DescrTab2:::.Q1,
        Q3 = DescrTab2:::.Q3
      ),
      reshape_rows = list(
        `Q1 - Q3` = list(args = c("Q1", "Q3"), fun = function(Q1, Q3) { paste0(Q1, "-", Q3) })),
      test_options = list(
        nonparametric = T,
        exact = T
      ),
      format_options = list(
        print_p = T,
        print_CI = F,
        print_Total = F,
        percent_suffix = "",
        combine_median_Q1_Q3 = T,
        Nmiss_row_percent = F,
        omit_missings_in_categorical_var = F,
        omit_missings_in_group = F,
        categorical_missing_percent_mode = "no_missing_percent",
        percent_accuracy = 0.1,
        combine_mean_sd=TRUE))

```
